language: node_js
node_js:
- 0.10.36
deploy:
  provider: heroku
  api_key:
    secure: TKUkCEsiV3eOBZeAGqUoYvaxdrNDDlUPqggj1f+KKLKQo3ooJwyhobdwr9vYKZyxpW1CNbYTpm05CnUCXkWGUTz47tqTTd6nf83bIkeX3JZzelTJgeSfDNI7jiJuFDZr8oeaS3J00C8CFPpvqH/Pn3YsF3Eo0Bhn49tm83/8SeE=
  app: fraxedas
  on:
    repo: fraxedas/eloqua-app
