SET MONGO_SERVICE=MongoDB
SET MONGO_DIR=C:\MongoDB
SET DATA_DIR=%MONGO_DIR%\data
SET LOG_DIR=%MONGO_DIR%\log
SET MONGO_INSTALLER=mongodb-win32-x86_64-2008plus-ssl-3.0.4-signed.msi
SET MONGO_INSTALLER_PATH=%USERPROFILE%\Downloads\%MONGO_INSTALLER%
SET MONGO_URL=https://fastdl.mongodb.org/win32/%MONGO_INSTALLER%

